export const FORETAG = {
  namn: "AIF Måleri AB",
  kortnamn: "AIF Måleri",
  ort: "Stockholm",
  grundat: 2022,
  telefon: "076-632 41 70",
  telefonLank: "+46766324170",
  epost: "info@aifmaleri.se",
  gatuadress: "Vingårdsgatan 13",
  postnummer: "117 58",
  adress: "Vingårdsgatan 13, 117 58 Stockholm",
  orgnr: "559374-8022",
  instagram: "https://www.instagram.com/aifmaleri/",
  instagramNamn: "@aifmaleri",
  oppettider: [
    { dag: "Måndag–fredag", tid: "07.00–16.00" },
    { dag: "Lördag", tid: "Stängt" },
    { dag: "Söndag", tid: "Stängt" },
  ],
} as const;
